### ISSUE TITLE
Exception when deleting CTD object

### ISSUE THREAD

**Issue by nickrsan** [nickrsan/seabird_ctd#4]
**[Original report](https://bitbucket.org/b195m/seabird_ctd/issue/4) by Nicholas Santos (Bitbucket: [nickrsan](https://bitbucket.org/nickrsan), GitHub: [nickrsan](https://github.com/nickrsan)).**

----------------------------------------

```
#!python

Exception ignored in: <bound method CTD.__del__ of <seabird_ctd.CTD object at 0x000002AD1A7F6978>>
Traceback (most recent call last):
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 487, in __del__
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 483, in close
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 228, in sleep
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 201, in _send_command
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 417, in check_data_for_records
  File "C:\Users\dsx\Code\icefish_backend\seabird_ctd\__init__.py", line 444, in find_and_insert_records
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

```

Could it be that it's trying to read after it sends the QS command?

**Comment by nickrsan** [comment]
**Original comment by Nicholas Santos (Bitbucket: [nickrsan](https://bitbucket.org/nickrsan), GitHub: [nickrsan](https://github.com/nickrsan)).**

----------------------------------------

Fixed by setting it so that when QS is sent, the object doesn't try to then read from the CTD before closing it. Unit test written, with some limitations noted in its docstring.
